const products = [
  {
    id: 1,
    name: "Wireless Mouse",
    description: "Ergonomic wireless mouse with long battery life and precision tracking.",
    price: 25.99,
    quantity: 150,
    inStock: true,
    category: "Electronics",
    brand: "Logitech",
    image: "/images/mouse.jpg",
  },
  {
    id: 2,
    name: "Running Shoes",
    description: "Lightweight running shoes designed for comfort and performance.",
    price: 80.0,
    quantity: 80,
    inStock: true,
    category: "Footwear",
    brand: "Nike",
    image: "/images/nike.jpg",
  },
  {
    id: 3,
    name: "Smartphone",
    description: "Latest model smartphone with high-resolution display and powerful processor.",
    price: 499.99,
    quantity: 50,
    inStock: true,
    category: "Electronics",
    brand: "Samsung",
    image: "/images/mobile.jpg",
  },
  {
    id: 4,
    name: "Denim Jacket",
    description: "Classic denim jacket with a comfortable fit and durable material.",
    price: 60.5,
    quantity: 40,
    inStock: true,
    category: "Clothing",
    brand: "Levi's",
    image: "/images/jacket.jpg",
  },
  {
    id: 5,
    name: "Electric Kettle",
    description: "Fast boiling electric kettle with automatic shutoff feature.",
    price: 35.0,
    quantity: 70,
    inStock: true,
    category: "Home Appliances",
    brand: "Philips",
    image: "/images/kettle.jpg",
  },
  {
    id: 6,
    name: "Bluetooth Speaker",
    description: "Portable Bluetooth speaker with rich sound and waterproof design.",
    price: 55.99,
    quantity: 120,
    inStock: true,
    category: "Electronics",
    brand: "JBL",
    image: "/images/jbl.jpg",
  },
  {
    id: 7,
    name: "Wrist Watch",
    description: "Stylish wrist watch with leather strap and water resistance.",
    price: 120.0,
    quantity: 30,
    inStock: true,
    category: "Accessories",
    brand: "Fossil",
    image: "/images/watch.jpg",
  },
  {
    id: 8,
    name: "Backpack",
    description: "Durable backpack with multiple compartments and ergonomic design.",
    price: 75.0,
    quantity: 90,
    inStock: true,
    category: "Bags",
    brand: "North Face",
    image: "/images/bag.jpg",
  },
  {
    id: 9,
    name: "Yoga Mat",
    description: "Non-slip yoga mat with cushioned surface for comfort.",
    price: 20.0,
    quantity: 200,
    inStock: true,
    category: "Fitness",
    brand: "Reebok",
    image: "/images/yogamat.jpg",
  },
  {
    id: 10,
    name: "Sunglasses",
    description: "UV-protected sunglasses with classic frame design.",
    price: 150.0,
    quantity: 25,
    inStock: true,
    category: "Accessories",
    brand: "Ray-Ban",
    image: "/images/glasses.jpg",
  },
  {
    id: 11,
    name: "Coffee Maker",
    description: "Compact coffee maker with quick brew technology.",
    price: 200.0,
    quantity: 35,
    inStock: true,
    category: "Home Appliances",
    brand: "Nespresso",
    image: "/images/coffee.jpg",
  },
  {
    id: 12,
    name: "Gaming Keyboard",
    description: "Mechanical gaming keyboard with customizable RGB lighting.",
    price: 100.0,
    quantity: 60,
    inStock: true,
    category: "Electronics",
    brand: "Razer",
    image: "/images/keyboard.jpg",
  },
];

module.exports = {products};
